SYMPTOM_RESPONSE_DATA = {
    "en": {
        "context_entities": {
            "symptom": {
                "headache": ["headache", "head pain", "migraine", "head hurts"],
                "fever": ["fever", "feverish", "high temperature", "chills"],
                "nausea": ["nausea", "nauseous", "vomiting", "throwing up"],
                "dizziness": ["dizzy", "dizziness", "lightheaded", "vertigo"],
                "fatigue": ["fatigue", "tired", "exhausted", "drained", "weakness"],
            },
            "cause": {
                "dehydration": ["dehydration", "dehydrated", "not drinking enough", "water intake is low"],
                "lack_of_sleep": ["lack of sleep", "didn't sleep", "did not sleep", "poor sleep", "sleep deprived", "no sleep"],
                "stress": ["stress", "stressed", "under pressure", "overwhelmed"],
                "screen_time": ["screen time", "too much screen", "looking at screens", "phone all day", "laptop all day"],
            },
            "supplement": {
                "creatine": ["creatine"],
                "protein_powder": ["protein powder", "whey", "mass gainer"],
                "preworkout": ["preworkout", "pre-workout"],
            },
            "medicine": {
                "paracetamol": ["paracetamol", "acetaminophen", "tylenol"],
                "ibuprofen": ["ibuprofen", "advil", "brufen"],
            },
            "severity": {
                "severe": ["severe", "very bad", "extreme", "intense"],
                "mild": ["mild", "slight", "small", "a little"],
            },
            "duration": {
                "since_yesterday": ["since yesterday"],
                "two_days": ["2 days", "two days", "for 2 days", "for two days"],
                "all_week": ["all week", "since all week", "for a week", "whole week"],
            },
            "emotional_context": {
                "stress": ["stress", "stressed", "overwhelmed"],
                "anxiety": ["anxious", "panic", "overthinking", "worried"],
                "low_mood": ["sad", "down", "depressed", "low"],
            },
        },
        "disease_keyword_map": {
            "malaria": ["malaria", "malarial fever"],
            "jaundice": ["jaundice", "yellow eyes", "yellow skin", "bilirubin"],
            "dengue": ["dengue", "breakbone fever", "platelets low"],
            "typhoid": ["typhoid", "enteric fever"],
            "flu": ["influenza", "the flu", "flu"],
            "migraine": ["migraine", "migraine attack"],
        },
        "keyword_map": {
            "fever": [
                "fever", "feverish", "high temperature", "temperature", "burning up",
                "hot body", "chills", "shivering", "body feels hot"
            ],
            "headache": [
                "headache", "head pain", "migraine", "head is hurting", "head hurts",
                "pressure in my head", "throbbing head", "pain in my head"
            ],
            "nausea": [
                "nausea", "nauseous", "queasy", "feel like vomiting", "feeling like vomiting",
                "sick to my stomach", "vomit", "vomiting", "throwing up"
            ],
            "cough": [
                "cough", "coughing", "dry cough", "wet cough", "phlegm", "mucus cough",
                "persistent cough", "hacking cough"
            ],
            "sore_throat": [
                "sore throat", "throat pain", "throat hurts", "painful swallowing",
                "scratchy throat", "swollen throat", "gala dard", "gala kharab"
            ],
            "dizziness": [
                "dizzy", "dizziness", "lightheaded", "lightheadedness", "room is spinning",
                "vertigo", "faint", "fainting", "almost fainted", "passed out"
            ],
            "stomach_pain": [
                "stomach pain", "abdominal pain", "stomach ache", "abdomen pain", "cramps",
                "belly pain", "pet dard", "gut pain", "pain in my stomach"
            ],
            "fatigue": [
                "fatigue", "tired", "exhausted", "drained", "no energy", "low energy",
                "weakness", "worn out", "body feels weak"
            ],
            "cold_flu": [
                "cold", "flu", "runny nose", "stuffy nose", "blocked nose", "sneezing",
                "body ache", "body pain", "congestion", "common cold", "viral", "chills"
            ],
        },
        "subtopics": {
            "malaria": {
                "label": "malaria concerns",
                "responses": [
                    "If malaria is a real possibility, it is worth treating this as something that needs proper medical evaluation rather than only home care. Fever, chills, sweating, body aches, and marked weakness are the kind of symptoms doctors usually want to assess quickly.",
                    "Malaria can overlap with other fever illnesses, so the practical next step is not to assume the cause too confidently. Hydration and rest matter, but testing and clinician guidance are important if there is fever with chills, exhaustion, or recent mosquito exposure.",
                    "With malaria-type illness, simple supportive care can help you feel a bit steadier, but it should not replace medical assessment. Fluids, rest, and paying attention to fever pattern, vomiting, or worsening weakness are useful while you arrange care.",
                    "If you are asking about malaria, I would focus less on self-diagnosing and more on getting checked if fever, chills, sweating, vomiting, or unusual weakness are present. Those symptoms deserve proper evaluation.",
                    "Malaria concerns usually call for a doctor visit rather than waiting it out at home. Rest and hydration still help in the meantime, but worsening fever or weakness should push you toward prompt care.",
                ],
                "closers": [
                    "Please seek urgent medical care if there is confusion, fainting, repeated vomiting, breathing trouble, or severe weakness with the fever illness.",
                    "A clinician should assess this promptly if malaria is suspected, especially with high fever, chills, vomiting, dehydration, or worsening drowsiness.",
                    "Do not wait on this if the person seems confused, very weak, short of breath, or unable to keep fluids down.",
                ],
            },
            "jaundice": {
                "label": "jaundice concerns",
                "responses": [
                    "If jaundice is the concern, the key point is that yellowing of the eyes or skin usually needs medical evaluation instead of only symptom care. Rest and hydration can help while you arrange care, but the cause matters.",
                    "Jaundice is less about home remedies and more about getting the right assessment. If you are noticing yellow eyes, dark urine, unusual tiredness, abdominal discomfort, or fever, a doctor visit is the sensible next move.",
                    "When jaundice is mentioned, I would avoid assuming it is minor. Supportive care like fluids and rest can still help, but proper testing is important because jaundice can come from several different medical causes.",
                    "Yellowing of the eyes or skin is something I would take seriously. It makes sense to keep hydrated and rest, but the practical step is to be evaluated rather than just monitor it loosely at home.",
                    "If this may be jaundice, clinician review matters more than trying multiple home-care ideas. Pay attention to fatigue, fever, abdominal pain, vomiting, or changes in urine or stool color while you arrange help.",
                ],
                "closers": [
                    "Please seek urgent care if jaundice comes with confusion, severe vomiting, strong abdominal pain, fainting, or trouble staying awake.",
                    "A doctor should assess jaundice promptly, especially if there is fever, pain, vomiting, or worsening weakness.",
                    "Do not wait on urgent help if the person becomes confused, very sleepy, dehydrated, or develops severe abdominal pain.",
                ],
            },
            "dengue": {
                "label": "dengue concerns",
                "responses": [
                    "If dengue is a possibility, fever care and hydration are important, but proper medical assessment matters too. Dengue can look like other viral illnesses early on, so it helps to take fever, body pain, vomiting, or unusual weakness seriously.",
                    "With dengue concerns, fluids and rest are useful first steps, but they are not the whole plan. A doctor should guide the next step if there is persistent fever, significant body pain, vomiting, or worsening weakness.",
                    "Dengue-type illness often needs closer watching than an ordinary mild viral fever. Hydration matters a lot, and it is worth paying attention to whether vomiting, abdominal pain, or unusual bleeding is showing up.",
                    "If you are worried about dengue, try not to rely only on guesswork. Fever, body aches, fatigue, and vomiting can overlap with other illnesses, so getting checked is the safer route if symptoms are substantial.",
                    "For possible dengue, rest and fluids are useful, but the main issue is whether the illness is intensifying. Persistent fever, weakness, vomiting, or signs of dehydration are good reasons to seek medical review.",
                ],
                "closers": [
                    "Please seek urgent medical care if there is severe vomiting, fainting, confusion, bleeding, strong abdominal pain, or trouble drinking fluids.",
                    "A clinician should see this promptly if dengue is suspected and fever is persistent, weakness is increasing, or vomiting is frequent.",
                    "Do not wait on this if the person seems very weak, dehydrated, confused, or develops chest pain or breathing trouble.",
                ],
            },
            "typhoid": {
                "label": "typhoid concerns",
                "responses": [
                    "If typhoid is being considered, the practical point is that it needs proper medical treatment rather than home care alone. Rest, hydration, and lighter food can help while you arrange care, but evaluation matters.",
                    "Typhoid can present like a persistent fever illness, so it makes sense to get checked instead of trying to manage it only with supportive care. Fluids, rest, and watching vomiting or abdominal symptoms are useful in the meantime.",
                    "With typhoid concerns, I would keep the home advice simple: hydrate, rest, and avoid heavy meals if the stomach is unsettled. The more important step is timely medical review.",
                    "If this might be typhoid, it is better to be assessed than to assume it will settle on its own. Persistent fever, weakness, stomach discomfort, or vomiting should push you toward a clinician.",
                    "Typhoid-type illness deserves proper follow-up. Supportive care can keep you steadier, but it should not replace testing and treatment advice.",
                ],
                "closers": [
                    "Please seek care promptly if there is persistent high fever, severe weakness, vomiting, confusion, or significant abdominal pain.",
                    "A doctor visit is the safer move if typhoid is suspected, especially when fever is not settling or hydration is becoming difficult.",
                    "Do not wait if there is fainting, confusion, repeated vomiting, or worsening weakness with the fever illness.",
                ],
            },
            "flu": {
                "label": "flu concerns",
                "responses": [
                    "If this sounds like flu, the first focus is usually rest, fluids, and not overexerting yourself while the body recovers. It helps to watch whether fever, cough, body aches, or weakness are easing or building.",
                    "Flu tends to hit harder than a mild common cold, so slowing down and hydrating well really matters. Warm fluids, rest, and keeping an eye on breathing and fever are sensible first steps.",
                    "With flu-type illness, practical care usually means hydration, sleep, lighter meals if needed, and letting the body rest instead of trying to push through work or study.",
                    "If you think it may be flu, try to treat it like a recovery day rather than a productivity day. Fluids, rest, and watching breathing, fever, and weakness are the useful basics.",
                    "Influenza-like symptoms often overlap with other viral illness, so I would focus on supportive care and warning signs rather than trying to label it too firmly on your own.",
                ],
                "closers": [
                    "Please seek medical care if flu symptoms come with breathing trouble, chest pain, confusion, dehydration, or a fever that is not settling.",
                    "A doctor visit makes sense sooner if the flu-like illness is getting worse instead of gradually easing.",
                    "Do not wait if there is shortness of breath, fainting, severe weakness, or trouble keeping fluids down.",
                ],
            },
            "migraine": {
                "label": "migraine concerns",
                "responses": [
                    "If this is a migraine-type headache, reducing light, noise, and screen exposure is often more helpful than trying to force through it. Hydration, rest, and a dark quiet space are sensible first steps.",
                    "Migraine often needs a calmer environment more than activity. Water, rest, and stepping away from bright screens or loud settings can help while you monitor whether the pain is settling.",
                    "For migraine-style pain, the practical basics are hydration, less sensory strain, and real rest. It also matters whether the headache feels familiar for you or very different from usual.",
                    "If you suspect migraine, I would try lowering screen use, resting your eyes, and noticing whether nausea, light sensitivity, or worsening pain are tagging along.",
                    "Migraine can be intensely disruptive, but it still helps to start with fluids, quiet, and reduced stimulation. The main caution is when the pattern feels unusually severe or unlike your typical headaches.",
                ],
                "closers": [
                    "Please seek urgent medical care if the headache is sudden and severe, comes with fainting or confusion, or feels very different from your usual pattern.",
                    "A clinician should assess this sooner if vomiting is severe, the headache keeps intensifying, or there are new concerning symptoms with it.",
                    "Do not wait on urgent help if migraine-like pain comes with weakness, confusion, chest pain, or trouble breathing.",
                ],
            },
            "fever": {
                "label": "fever",
                "responses": [
                    "For fever, fluids and rest matter more than pushing through the day. If you can, sip water regularly, stay in light clothing, and keep an eye on whether the temperature is rising or settling.",
                    "A mild fever often improves with rest, hydration, and a cooler room. If you have a thermometer, checking it now and then can help you decide whether this is easing or moving in the wrong direction.",
                    "When fever shows up, the practical basics are water, rest, and not overheating yourself with heavy blankets. It also helps to notice whether chills, cough, sore throat, or body aches are coming with it.",
                    "If this is a fever, try to slow your day down for a bit and focus on fluids. The bigger question is whether it is staying mild or climbing higher despite rest.",
                    "Fever can dry you out quickly, so hydration is one of the best first steps. Small sips, lighter meals, and some quiet rest are usually more helpful than trying to power through.",
                    "A temperature-related illness often needs simple care first: fluids, rest, and watching for new symptoms like cough, sore throat, or worsening weakness.",
                ],
                "closers": [
                    "Please get medical care promptly if the fever is very high, lasts more than a couple of days, or comes with confusion, breathing trouble, or chest pain.",
                    "If the fever keeps climbing, you are getting hard to wake, or breathing feels off, it is safer to be checked by a clinician.",
                    "A doctor visit makes sense sooner if the fever is intense, persistent, or paired with dehydration or worsening breathing symptoms.",
                ],
            },
            "headache": {
                "label": "headache",
                "responses": [
                    "With a headache, the simple causes are often worth checking first: dehydration, missed meals, poor sleep, or too much screen strain. Water, food if you have not eaten, and a quieter room may help.",
                    "A headache sometimes settles with rest, less light and screen exposure, and good hydration. If your neck is tight or your eyes feel strained, giving yourself a break can make a real difference.",
                    "For headache, I would start with the basics instead of pushing through it: drink some water, step away from bright screens for a while, and rest your eyes if you can.",
                    "Headaches can come from tension, fever, poor sleep, or not eating enough. A calm room, fluids, and a short rest are often the most useful first moves.",
                    "If this feels like a headache rather than general illness, try lowering light, noise, and screen use for a bit. It is also worth noticing if the pain is new, unusually strong, or tied to fever.",
                    "The first pass for headache care is often hydration, rest, and reducing strain. If you have been staring at a phone or laptop for hours, giving your eyes a break is a sensible step.",
                ],
                "closers": [
                    "Please seek urgent care if this is the worst headache you have had, starts suddenly, follows a fainting spell, or comes with confusion, weakness, or chest pain.",
                    "A clinician should check this sooner if the headache is severe, keeps getting stronger, or is paired with fever, vomiting, or unusual confusion.",
                    "Emergency help is the safer option if the headache is sudden and intense or if you also feel faint, confused, or short of breath.",
                ],
            },
            "nausea": {
                "label": "nausea",
                "responses": [
                    "For nausea, it usually helps to go gently with both fluids and food. Small sips of water or an oral rehydration drink, plus bland foods when you feel ready, are often easier than large meals.",
                    "Nausea is easier to manage when you do less at once: slow sips, a quiet place, and light foods like toast, rice, or crackers if your stomach can tolerate them.",
                    "If you feel nauseous, focus first on staying hydrated rather than eating a full meal. Tiny, steady sips are often better tolerated than drinking a lot at once.",
                    "When nausea starts, rich or greasy food usually makes things harder. Bland food later, fluids now, and a little rest often work better.",
                    "A practical way to handle nausea is to keep fluids going in small amounts and give your stomach a break. If vomiting is happening too, the key question is whether you can keep anything down.",
                    "Nausea can wear you out quickly, so pacing matters. Try slow hydration, light foods only if tolerated, and a calmer position rather than moving around a lot.",
                ],
                "closers": [
                    "Please get medical help if vomiting becomes frequent, you cannot keep fluids down, or you notice fainting, confusion, or severe stomach pain.",
                    "A doctor should evaluate this sooner if the nausea is intense, turns into repeated vomiting, or leaves you too weak or dizzy to function.",
                    "Urgent care is safer if you are throwing up again and again, getting dehydrated, or becoming confused or faint.",
                ],
            },
            "cough": {
                "label": "cough",
                "responses": [
                    "For a cough, rest, fluids, and warm drinks can be more useful than forcing conversation or activity. It also helps to notice whether this is dry, chesty, or bringing up mucus.",
                    "A cough often improves with hydration and avoiding things that irritate the throat, like smoke, dust, or very cold air. Warm liquids can sometimes ease the urge to keep coughing.",
                    "If you are coughing a lot, slowing things down and drinking fluids regularly can help keep the throat and chest from feeling even more irritated.",
                    "With cough, the useful detail is what kind it is: dry, productive, mild, or keeping you from sleeping. Warm fluids, rest, and reducing throat irritation are good first steps either way.",
                    "A cough that comes with cold symptoms often needs supportive care more than anything dramatic at first. Fluids, rest, and watching your breathing matter most.",
                    "If the cough is wearing you out, try warm fluids, a bit of vocal rest, and keeping an eye on whether breathing feels normal or tighter than usual.",
                ],
                "closers": [
                    "Please seek care urgently if coughing comes with breathing trouble, chest pain, confusion, or you feel faint.",
                    "A clinician should check this promptly if the cough is worsening fast, affecting breathing, or comes with high fever or chest pain.",
                    "If you are short of breath, tight in the chest, or too weak to catch your breath comfortably, do not wait on this.",
                ],
            },
            "sore_throat": {
                "label": "sore throat",
                "responses": [
                    "A sore throat often responds to fluids, warm drinks, and giving your voice a bit of rest. Softer foods can also be easier if swallowing feels irritating.",
                    "For sore throat, hydration and warmth usually help more than pushing through it. Tea, warm water, soup, and less strain on the throat can settle things a little.",
                    "If your throat is hurting, try to keep fluids up and avoid anything too rough or spicy for now. A calmer throat often starts with warmth and less irritation.",
                    "Sore throat can come with a cold, flu, or just local irritation. Warm liquids, rest, and softer foods are a reasonable first response while you see how it evolves.",
                    "When swallowing hurts, small sips and gentle foods are usually easier than large meals. It is also useful to notice whether fever or cough is showing up with it.",
                    "For throat pain, the practical basics are fluids, rest, and reducing anything that keeps scraping or drying the throat out.",
                ],
                "closers": [
                    "Please get checked sooner if swallowing becomes very hard, breathing feels affected, or the sore throat comes with high fever or confusion.",
                    "A doctor visit is wise if throat pain keeps escalating, you cannot take fluids well, or there is chest pain or breathing difficulty.",
                    "Seek urgent help if the throat symptoms are making it hard to breathe, hard to swallow liquids, or you are becoming weak or confused.",
                ],
            },
            "dizziness": {
                "label": "dizziness",
                "responses": [
                    "If you feel dizzy, the safest first move is to sit or lie down rather than try to push through it. Water, a slower position change, and a little rest are more important than staying active right now.",
                    "Dizziness can come from dehydration, not eating enough, illness, or sudden standing. Pause what you are doing, steady yourself, and give your body a few quiet minutes.",
                    "When dizziness hits, safety comes first: sit down, avoid sudden movement, and take some fluids if you can. It is also worth asking yourself whether you have eaten recently.",
                    "For dizziness, try to reduce movement and let your body settle before doing anything else. Standing up too quickly or being underhydrated can make it worse.",
                    "A lightheaded or spinning feeling deserves caution. Rest somewhere safe, hydrate, and notice whether it passes or keeps returning.",
                    "If the room feels like it is moving or you feel unsteady, slow everything down. Sitting, fluids, and avoiding quick position changes are sensible first steps.",
                ],
                "closers": [
                    "Please seek urgent care if dizziness leads to fainting, chest pain, breathing trouble, confusion, or if you cannot safely stay upright.",
                    "A clinician should assess this promptly if you passed out, nearly passed out, or the dizziness is severe and not settling.",
                    "Do not wait on emergency help if you are fainting, confused, short of breath, or having chest pain with the dizziness.",
                ],
            },
            "stomach_pain": {
                "label": "stomach pain",
                "responses": [
                    "For stomach pain, I would go gently at first: fluids, lighter food, and rest rather than a heavy meal. The useful thing to notice is whether this feels crampy, sharp, or tied to vomiting or diarrhea.",
                    "Stomach pain is easier to judge when you look at the pattern. Try to rest, keep hydrated, and notice whether the pain comes in waves, stays in one spot, or gets worse after eating.",
                    "If your stomach is hurting, a lighter approach often helps early on: small sips, bland food only if tolerated, and a little quiet rest.",
                    "With abdominal discomfort, the important clues are whether the pain is mild and easing or becoming stronger and harder to ignore. Fluids matter either way.",
                    "For stomach pain, I would not rush heavy food. Hydration, a simpler diet, and paying attention to vomiting, diarrhea, or worsening pain are the more useful steps.",
                    "Sometimes stomach pain settles with rest and a gentle diet, but it matters if the pain is sharp, severe, or happening with repeated vomiting.",
                ],
                "closers": [
                    "Please get medical help if the stomach pain is severe, keeps worsening, or comes with fainting, confusion, or repeated vomiting.",
                    "A doctor should evaluate this sooner if the pain is strong, one-sided, or you cannot keep fluids down.",
                    "Urgent care is the safer move if the abdominal pain becomes intense or you are vomiting a lot, getting weak, or feeling faint.",
                ],
            },
            "fatigue": {
                "label": "fatigue",
                "responses": [
                    "If this is fatigue, I would treat it like your body is asking for recovery rather than more pressure. Rest, fluids, and a bit of food if you have not eaten are sensible first steps.",
                    "Low energy can come from poor sleep, illness, dehydration, or not eating enough. Before pushing yourself, check the basics: rest, hydration, and whether other symptoms are tagging along.",
                    "Fatigue usually calls for a reset more than motivation. Slow down, drink some water, and see whether sleep, food, or a possible illness could be part of it.",
                    "When you feel unusually drained, it helps to look at the whole picture: sleep, fever, body aches, stress, and hydration often all matter more than just willpower.",
                    "For tiredness that feels physical, start with gentle recovery rather than forcing productivity. Water, food, and real rest tend to tell you more than trying to power through.",
                    "If the body feels weak or exhausted, I would pay attention to whether this is just low energy or part of a wider illness with fever, cough, pain, or dizziness.",
                ],
                "closers": [
                    "Please get checked if the fatigue is sudden, severe, or comes with chest pain, breathing trouble, confusion, or fainting.",
                    "A clinician should see this sooner if the weakness is getting worse or you are too drained to stay hydrated or function normally.",
                    "Urgent help is safer if the fatigue is extreme and paired with dizziness, chest pain, confusion, or trouble breathing.",
                ],
            },
            "cold_flu": {
                "label": "cold or flu symptoms",
                "responses": [
                    "This sounds more like a cold or flu pattern, so supportive care is usually the first lane: fluids, rest, and letting your body recover instead of staying overactive.",
                    "With cold or flu-type symptoms, hydration, sleep, and a slower day are often the most useful first steps. It also helps to watch whether fever or cough is getting stronger.",
                    "Runny nose, body aches, cough, or chills often point toward a viral illness. The practical response is usually rest, fluids, and keeping an eye on breathing and temperature.",
                    "If this feels like a cold or flu, treat recovery like the priority for now. Warm fluids, rest, and paying attention to how the symptoms evolve are usually more helpful than doing too much.",
                    "Cold and flu symptoms often overlap, so I would focus on comfort and warning signs rather than trying to label it perfectly. Fluids, rest, and watching the fever and breathing matter most.",
                    "A viral-feeling illness usually needs time plus basics: water, sleep, and not ignoring symptoms that are getting sharper instead of easing.",
                ],
                "closers": [
                    "Please seek care promptly if breathing becomes difficult, chest pain appears, fever is high or persistent, or you are getting confused or faint.",
                    "A doctor visit makes sense sooner if the cold or flu symptoms are worsening rather than settling, especially with breathing trouble or dehydration.",
                    "Do not wait on this if the illness is bringing chest pain, shortness of breath, fainting, or confusion.",
                ],
            },
        },
        "severe_keywords": [
            "breathing trouble", "trouble breathing", "difficulty breathing", "shortness of breath",
            "cannot breathe", "can't breathe", "chest pain", "fainting", "fainted", "passed out",
            "confusion", "confused", "severe vomiting", "vomiting repeatedly", "vomiting constantly",
            "keep vomiting", "cannot keep fluids down", "can't keep fluids down", "cannot keep anything down",
            "can't keep anything down", "very weak", "hard to wake"
        ],
        "urgent_fallbacks": [
            "Because severe warning signs may be involved, urgent medical care is the safest next step.",
            "The symptoms you described can become serious, so please seek urgent in-person medical help now.",
            "This has enough red flags that I would not rely on home care alone. Please get urgent medical attention.",
        ],
    },
    "hi": {
        "context_entities": {
            "symptom": {
                "headache": ["sir dard", "sar dard", "headache", "migraine"],
                "fever": ["bukhar", "fever", "temperature"],
                "nausea": ["ulti", "nausea", "vomiting"],
                "dizziness": ["chakkar", "dizziness", "dizzy"],
                "fatigue": ["thakan", "kamzori", "weakness"],
            },
            "cause": {
                "dehydration": ["dehydration", "paani kam", "kam paani", "paani nahi piya"],
                "lack_of_sleep": ["neend kam", "sleep nahi", "lack of sleep"],
                "stress": ["stress", "tanav", "tension"],
                "screen_time": ["screen time", "mobile zyada", "laptop zyada"],
            },
            "supplement": {
                "creatine": ["creatine"],
                "protein_powder": ["protein powder", "whey"],
                "preworkout": ["preworkout", "pre-workout"],
            },
            "medicine": {
                "paracetamol": ["paracetamol", "acetaminophen"],
                "ibuprofen": ["ibuprofen", "brufen"],
            },
            "severity": {
                "severe": ["zyada", "bahut zyada", "intense", "severe"],
                "mild": ["halka", "mild", "thoda"],
            },
            "duration": {
                "since_yesterday": ["kal se", "since yesterday"],
                "two_days": ["2 din", "do din", "2 days"],
                "all_week": ["poore hafte", "all week", "hafte bhar"],
            },
            "emotional_context": {
                "stress": ["stress", "tanav", "tension"],
                "anxiety": ["ghabrahat", "panic", "chinta"],
                "low_mood": ["udas", "low", "depressed"],
            },
        },
        "disease_keyword_map": {
            "malaria": ["malaria", "malaria fever"],
            "jaundice": ["jaundice", "peeliya", "peelia", "yellow eyes"],
            "dengue": ["dengue"],
            "typhoid": ["typhoid"],
            "flu": ["flu", "influenza"],
            "migraine": ["migraine", "aadha sir dard"],
        },
        "keyword_map": {
            "fever": ["bukhar", "fever", "bukhaar", "body garam", "kapkapi", "thand lag rahi"],
            "headache": ["sir dard", "sar dard", "headache", "migraine", "sir bhaari"],
            "nausea": ["ulti", "nausea", "mann ghabra raha", "vomiting", "ulti jaisa"],
            "cough": ["khansi", "khasi", "cough", "dry cough", "balgam"],
            "sore_throat": ["gala dard", "gala kharab", "sore throat", "gale me dard", "throat pain"],
            "dizziness": ["chakkar", "dizziness", "dizzy", "behosh", "lightheaded"],
            "stomach_pain": ["pet dard", "stomach pain", "pet me dard", "cramps", "abdominal pain"],
            "fatigue": ["thakan", "kamzori", "fatigue", "weakness", "energy nahi"],
            "cold_flu": ["sardi", "jukam", "flu", "cold", "naak band", "runny nose"],
        },
        "severe_keywords": [
            "saans phool rahi", "sans phool rahi", "breathing trouble", "chest pain", "seene mein dard",
            "seene me dard", "behosh", "fainting", "confusion", "bahut ulti", "ulti ruk nahi rahi",
            "bar bar ulti", "fluid nahi ruk raha"
        ],
        "urgent_fallbacks": [
            "Agar severe warning signs ho rahe hain to turant doctor ya emergency care lena zyada safe rahega.",
            "Jo red flags dikh rahe hain unke saath home care par depend karna theek nahi hoga. Please urgent medical help lijiye.",
        ],
    },
    "hinglish": {
        "context_entities": {
            "symptom": {
                "headache": ["sir dard", "sar dard", "headache", "migraine"],
                "fever": ["bukhar", "fever", "temperature"],
                "nausea": ["ulti", "nausea", "vomiting"],
                "dizziness": ["chakkar", "dizziness", "dizzy"],
                "fatigue": ["thakan", "kamzori", "weakness", "drained"],
            },
            "cause": {
                "dehydration": ["dehydration", "dehydrated", "paani kam", "water intake low"],
                "lack_of_sleep": ["lack of sleep", "sleep nahi", "poor sleep"],
                "stress": ["stress", "tension", "overwhelmed"],
                "screen_time": ["screen time", "phone zyada", "laptop zyada"],
            },
            "supplement": {
                "creatine": ["creatine"],
                "protein_powder": ["protein powder", "whey"],
                "preworkout": ["preworkout", "pre-workout"],
            },
            "medicine": {
                "paracetamol": ["paracetamol", "acetaminophen"],
                "ibuprofen": ["ibuprofen", "brufen"],
            },
            "severity": {
                "severe": ["severe", "intense", "bahut zyada"],
                "mild": ["mild", "thoda", "slight"],
            },
            "duration": {
                "since_yesterday": ["since yesterday", "kal se"],
                "two_days": ["2 days", "2 din", "do din"],
                "all_week": ["all week", "hafte bhar", "poore week"],
            },
            "emotional_context": {
                "stress": ["stress", "tension"],
                "anxiety": ["anxious", "panic", "overthinking"],
                "low_mood": ["sad", "down", "low", "depressed"],
            },
        },
        "disease_keyword_map": {
            "malaria": ["malaria", "malaria fever"],
            "jaundice": ["jaundice", "peeliya", "yellow eyes"],
            "dengue": ["dengue"],
            "typhoid": ["typhoid"],
            "flu": ["flu", "influenza"],
            "migraine": ["migraine", "aadha sir dard"],
        },
        "keyword_map": {
            "fever": ["bukhar", "fever", "feverish", "body garam", "chills"],
            "headache": ["sir dard", "sar dard", "headache", "migraine", "sir bhaari"],
            "nausea": ["ulti", "nausea", "nauseous", "vomiting", "mann ghabra raha"],
            "cough": ["khansi", "khasi", "cough", "dry cough", "phlegm"],
            "sore_throat": ["gala dard", "gala kharab", "sore throat", "throat hurts", "gale me dard"],
            "dizziness": ["chakkar", "dizziness", "dizzy", "lightheaded", "behosh"],
            "stomach_pain": ["pet dard", "stomach pain", "pet me dard", "cramps", "abdominal pain"],
            "fatigue": ["thakan", "fatigue", "kamzori", "weakness", "no energy"],
            "cold_flu": ["sardi", "cold", "flu", "jukam", "runny nose", "naak band"],
        },
        "severe_keywords": [
            "breathing trouble", "saans phool rahi", "chest pain", "behosh", "fainting",
            "confusion", "severe vomiting", "ulti ruk nahi rahi", "keep vomiting",
            "can't keep fluids down", "cannot keep fluids down"
        ],
        "urgent_fallbacks": [
            "Agar severe red flags aa rahe hain to urgent medical care lena safest next step hoga.",
            "Ye symptoms serious ho sakte hain, isliye sirf home care par wait mat karo. Please urgent doctor help lo.",
        ],
    },
}


RULE_RESPONSE_DATA = {
    "en": {
        "topic_labels": {
            "anxiety": "anxiety",
            "stress": "stress",
            "fatigue": "low energy",
            "physical_discomfort": "physical discomfort",
            "general": "what you are dealing with",
        },
        "general_query": {
            "openers": [
                "I am here with you.",
                "Thanks for saying that out loud.",
                "I am listening.",
                "We can slow this down together.",
                "I am with you on this.",
            ],
            "repeat_openers": [
                "I am still with you.",
                "We can stay with this a bit longer.",
                "I hear that this is still sitting with you.",
                "Let us keep working through it together.",
                "We can take another pass at this.",
            ],
            "templates": [
                "Tell me the part that feels most important right now, and I will respond step by step.",
                "You can say what happened, what you are feeling, or what kind of help you want first.",
                "If you want, describe the main feeling or symptom in one line and I will make the next step clearer.",
                "Start wherever it feels easiest: what happened, what hurts, or what feels heavy.",
                "Give me the simplest version of it, and I will help from there.",
                "If this is about your mind or your body, tell me which one feels louder right now.",
                "You do not need perfect words here. Just tell me what is going on.",
                "Name the biggest thing on your mind, and we will work from that.",
                "If you want support, tell me whether this feels more like stress, anxiety, sadness, or a physical symptom.",
                "You can begin with one short sentence, and I will help you unpack it.",
            ],
            "closers": [
                "We can take it one message at a time.",
                "You do not have to sort it all out alone.",
                "I will keep this practical and supportive.",
                "We can make this more manageable.",
                "I am here for the next step too.",
            ],
        },
        "greeting": {
            "openers": ["Hi.", "Hello.", "Hey there.", "Good to hear from you.", "Hey."],
            "repeat_openers": ["Hi again.", "Hey, I am here.", "Still here with you.", "Hello again.", "Hey again."],
            "templates": [
                "How are you doing today?",
                "What is on your mind?",
                "How can I help today?",
                "What would you like to talk about?",
                "Hope your day is going okay so far.",
                "Tell me what you need help with.",
            ],
            "closers": [
                "We can keep it simple.",
                "I am ready when you are.",
                "You can start anywhere.",
                "Happy to chat.",
                "I am listening.",
            ],
        },
        "gratitude": {
            "openers": ["You are welcome.", "Anytime.", "Glad to help.", "Of course.", "Happy to help."],
            "repeat_openers": ["Always welcome.", "Anytime at all.", "Glad I could help again.", "Of course.", "Happy to be here."],
            "templates": [
                "I am glad that helped.",
                "I am happy to be useful.",
                "Glad it made things a little easier.",
                "That means a lot, thank you.",
                "I am here whenever you need another hand.",
                "Happy to stay with you if there is more to talk through.",
            ],
            "closers": [
                "We can keep going if you want.",
                "Feel free to send the next thing on your mind.",
                "I am here if you need more help.",
                "Anytime you want to continue.",
                "Just message again whenever you need.",
            ],
        },
        "goodbye": {
            "openers": ["Take care.", "Bye for now.", "Goodnight.", "See you soon.", "Alright, take care."],
            "repeat_openers": ["Take care again.", "Bye for now.", "Wishing you a calm rest of the day.", "See you soon.", "Goodnight."],
            "templates": [
                "I will be here if you want to come back later.",
                "Hope the rest of your day feels a little lighter.",
                "Be gentle with yourself today.",
                "Come back anytime you want to talk.",
                "Wishing you a peaceful rest of the day.",
                "You can always pick this up again later.",
            ],
            "closers": [
                "See you later.",
                "Talk soon.",
                "I am here whenever you need.",
                "Take it easy.",
                "Bye.",
            ],
        },
        "casual_checkin": {
            "openers": ["I am doing well, thanks.", "Doing okay here.", "I am here and ready to help.", "I am doing alright.", "Pretty steady here."],
            "repeat_openers": ["Still doing okay here.", "I am here with you.", "All good on my side.", "Still ready to help.", "Doing fine here."],
            "templates": [
                "What about you, how has your day been?",
                "How are you holding up today?",
                "What is going on with you right now?",
                "How is your day treating you so far?",
                "What is up on your side?",
                "How have things been feeling lately?",
            ],
            "closers": [
                "You can keep it casual or tell me something real.",
                "I am happy to chat or help with something specific.",
                "Whatever is on your mind is fine.",
                "You can tell me as little or as much as you want.",
                "I am here either way.",
            ],
        },
        "solution_request": {
            "openers": [
                "We can make this simpler.",
                "Let us focus on what helps next.",
                "There are a few steady ways to approach this.",
                "We can turn this into one clear next move.",
                "Let us keep this practical.",
            ],
            "repeat_openers": [
                "Since this is still coming up, let us try a slightly different angle.",
                "Because this is repeating, I want to give you a fresh next step.",
                "Let us adjust the approach a bit.",
                "We can try a gentler version this time.",
                "I want to give you a different way into it.",
            ],
            "templates": [
                "Start with one small action for {topic}: drink some water, sit down, and slow your breathing for a minute before deciding what comes next.",
                "For {topic}, I would keep the next step short: pause, notice what feels strongest, and choose one helpful action instead of trying to fix everything at once.",
                "Try this: name the problem, lower the pressure, and do one thing that gives relief in the next ten minutes.",
                "A good next move is to reduce intensity first, then think. Slow breath, loosen your shoulders, and pick one manageable step.",
                "If you want steadier ground, begin with basics: water, a slower breath, and one small decision instead of ten.",
                "The most useful approach here is usually: settle your body first, then decide what needs attention now and what can wait.",
                "Give yourself a tiny plan: one calming step, one practical step, and one thing you do not need to solve yet.",
                "For {topic}, small actions usually work better than pushing harder. Pick the easiest helpful step and start there.",
                "Try reducing the pressure around this for a moment, then choose one action that helps your body or mind feel safer.",
                "The next step does not have to be big. One calm breath cycle and one useful action is enough to start.",
            ],
            "closers": [
                "If you want, send the exact situation and I can narrow the advice.",
                "We can tailor the next step if you tell me what part feels hardest.",
                "I can help you make that more specific if you want.",
                "Tell me what you have already tried and I will adjust from there.",
                "If you give me one more detail, I can make this more precise.",
            ],
        },
        "symptom_report": {
            "openers": [
                "That sounds uncomfortable.",
                "I can see why that would get your attention.",
                "That does sound real and draining.",
                "I am taking that seriously.",
                "That sounds hard to sit with.",
            ],
            "repeat_openers": [
                "Since the symptom is still there, let us look at it a little differently.",
                "Because this is continuing, it makes sense to check in again.",
                "I hear that this has not eased yet.",
                "If it is repeating, we should stay practical and watchful.",
                "Let us reassess it together for a moment.",
            ],
            "templates": [
                "Notice when the {topic} started, whether it is getting stronger, and what other symptoms are showing up beside it.",
                "For {topic}, it helps to check three things: how intense it is, how long it has been going on, and whether anything makes it worse.",
                "Try to slow down and observe the pattern: timing, severity, and any warning signs that are traveling with it.",
                "The useful next step is to monitor the symptom clearly instead of guessing. Track when it began and what changed around it.",
                "With {topic}, the details matter: duration, intensity, and any red-flag symptoms are the first things I would notice.",
                "Start by checking whether this is mild and settling, or strong and worsening. That tells us a lot.",
                "If your body is doing something unusual, it helps to stay concrete: what is happening, how often, and what else came with it.",
                "Try not to ignore it or panic about it. Just gather the clearest signs: where it is, how strong it is, and whether it is spreading or worsening.",
                "For a symptom like this, I would pay attention to hydration, rest, and whether any severe warning signs are present.",
                "The next helpful move is observation plus care: slow down, rest if you can, and note the strongest symptom clearly.",
            ],
            "closers": [
                "If you tell me the main symptom and any warning signs, I can guide the next step more clearly.",
                "Send the strongest symptom in one line and I will make the response more specific.",
                "If you add duration and severity, I can be more precise.",
                "Tell me what symptom is most noticeable right now and I will narrow it down.",
                "If you list the top two symptoms, I can respond more clearly.",
            ],
        },
        "emotional_support": {
            "openers": [
                "I am sorry this feels so heavy.",
                "That sounds like a lot to carry.",
                "I can hear that this is weighing on you.",
                "It makes sense that you are feeling stretched by this.",
                "I am glad you said it instead of holding it alone.",
            ],
            "repeat_openers": [
                "I hear that this feeling is still with you.",
                "Since this is repeating, let us respond to it with a little more care.",
                "If this keeps coming back, it deserves patience.",
                "I can see this has not loosened its grip yet.",
                "Let us meet the same feeling with a slightly different response.",
            ],
            "templates": [
                "You do not have to solve the whole feeling right now. Start with one steadying action and let the rest wait for a moment.",
                "When {topic} feels loud, the first goal is not perfection. It is a little more safety, a little more air, and one manageable next step.",
                "Try lowering the pressure for the next few minutes: unclench your jaw, soften your shoulders, and let your breathing slow down.",
                "What you are feeling matters. For now, keep it small: breathe out slowly, sip water, and name the next gentle thing you need.",
                "If your mind feels crowded, do less for a moment. One breath cycle, one sip of water, one kind sentence to yourself.",
                "You are allowed to pause before fixing anything. Calm the body a little, and clarity usually returns more easily.",
                "This sounds emotionally exhausting. I would focus on steadiness first, not productivity.",
                "Try not to argue with every thought right now. Help your body feel safer first, then we can sort through the thoughts.",
                "When a feeling keeps pressing on you, small grounding steps often help more than forcing yourself to be okay.",
                "You deserve a slower, kinder next minute than the one your mind may be pushing you into.",
            ],
            "closers": [
                "If you want, tell me whether this feels more like anxiety, sadness, stress, or loneliness.",
                "You can send one line about what triggered it, and I will stay with you in it.",
                "If you want a more tailored response, tell me what happened just before this feeling got stronger.",
                "I can help you sort the feeling if you want to name it more specifically.",
                "Tell me what feels heaviest right now and I will respond to that part.",
            ],
        },
        "emergency": {
            "openers": [
                "I am really glad you said this.",
                "Thank you for saying it directly.",
                "I am taking this seriously.",
                "I am glad you reached out right now.",
                "This matters a lot.",
            ],
            "repeat_openers": [
                "I am staying focused on your safety.",
                "Because this is repeating, I want to keep the next steps very clear.",
                "I am still taking this seriously.",
                "Let us keep the safety steps simple and direct.",
                "Your safety is still the priority here.",
            ],
            "templates": [
                "Please move toward immediate human support now: call emergency services or a crisis line, or go to the nearest emergency department if you might act on this.",
                "Do not stay alone with this if you can help it. Contact someone you trust right now and tell them you need them with you.",
                "Put distance between yourself and anything you could use to hurt yourself, and reach out for urgent support immediately.",
                "If you feel at risk of acting on this, call emergency services now or ask someone nearby to call for you.",
                "Please text or call a trusted person right now and say clearly that you do not feel safe on your own.",
                "Your next step should be real-world support, not handling this alone. Stay near another person if you can.",
                "If you are in immediate danger, go to the nearest emergency room or call local emergency help now.",
                "Make safety the only job for the next few minutes: get near people, remove harmful items, and contact urgent support.",
                "Please do one direct safety action now: call, text, or go to someone in person and tell them this is urgent.",
                "If the urge feels active, seek emergency help immediately and do not stay by yourself.",
            ],
            "closers": [
                "If you can reply with 'I am safe' or 'I am not safe,' I will respond accordingly.",
                "Send one short reply telling me whether someone is with you.",
                "Reply with whether you are alone right now.",
                "Tell me if you have reached someone yet.",
                "If you can, send one line telling me your immediate safety status.",
            ],
        },
    },
    "hi": {
        "topic_labels": {
            "anxiety": "ghabrahat",
            "stress": "tanav",
            "fatigue": "thakan",
            "physical_discomfort": "body symptoms",
            "general": "jo chal raha hai",
        },
        "general_query": {
            "openers": ["Main yahin hoon.", "Main sun raha hoon.", "Aap aaraam se bata sakte hain.", "Theek hai, hum isse saath dekhte hain.", "Boliye, main dhyan se sun raha hoon."],
            "repeat_openers": ["Main abhi bhi yahin hoon.", "Hum isse thoda aur clearly dekh sakte hain.", "Lag raha hai ye baat abhi bhi heavy hai.", "Chaliye isko phir se aaraam se pakadte hain.", "Hum isko saath mein samajhte rehte hain."],
            "templates": [
                "Aap jo sabse important lag raha hai woh ek line mein bata dijiye, main wahan se help karunga.",
                "Aap chahein to batayein kya hua, kaisa feel ho raha hai, ya kis tarah ki help chahiye.",
                "Bas simple shabdon mein likhiye, perfect likhne ki zaroorat nahi hai.",
                "Jo baat sabse zyada dimaag mein chal rahi hai, wahi se shuru kijiye.",
                "Aap feeling, symptom, ya situation mein se jo aasaan lage usse start kar sakte hain.",
                "Ek chhoti si line bhi kaafi hai, main usko aage samajhne mein help karunga.",
                "Aap bas bataiye abhi sabse zyada kya pareshaan kar raha hai.",
                "Jo cheez sabse loud lag rahi hai, usse shuru karein.",
                "Agar mind ya body mein se koi ek zyada disturb kar raha hai, woh bata dijiye.",
                "Seedha sa batayein abhi aapko kis baat mein support chahiye.",
            ],
            "closers": ["Hum ek-ek message mein aage badhenge.", "Aapko sab kuch akela handle nahi karna hai.", "Main isse simple aur supportive rakhunga.", "Hum isko manageable banayenge.", "Main next message mein bhi aapke saath hoon."],
        },
        "greeting": {
            "openers": ["Namaste.", "Hello.", "Hi.", "Aap se sun kar achha laga.", "Hey."],
            "repeat_openers": ["Namaste phir se.", "Hi again.", "Main yahin hoon.", "Hello dobara.", "Aap se phir baat ho rahi hai."],
            "templates": [
                "Aaj aap kaise ho?",
                "Boliye, aaj kis baat mein help chahiye?",
                "Kya chal raha hai aaj?",
                "Aap kis baat se start karna chahenge?",
                "Aap aaraam se bol sakte hain.",
                "Jo mann mein ho woh bata dijiye.",
            ],
            "closers": [
                "Hum simple tareeke se baat kar sakte hain.",
                "Main ready hoon.",
                "Aap kahin se bhi start kar sakte hain.",
                "Main sun raha hoon.",
                "Aaraam se batayein.",
            ],
        },
        "gratitude": {
            "openers": ["Aapka swagat hai.", "Kabhi bhi.", "Khushi hui help karke.", "Zaroor.", "Anytime."],
            "repeat_openers": ["Hamesha welcome.", "Kabhi bhi message kijiye.", "Khushi hui phir se help karke.", "Bilkul.", "Anytime."],
            "templates": [
                "Achha laga ki ye helpful raha.",
                "Mujhe khushi hai ki thoda kaam aaya.",
                "Agar isse thoda ease mila ho to achhi baat hai.",
                "Shukriya, ye sun kar achha laga.",
                "Jab chahein phir message kar sakte hain.",
                "Agar aur baat karni ho to main yahin hoon.",
            ],
            "closers": [
                "Hum aage bhi baat kar sakte hain.",
                "Aap chahein to next message bhej sakte hain.",
                "Main yahin hoon agar aur help chahiye.",
                "Kabhi bhi wapas aa sakte hain.",
                "Jab zaroorat ho message kijiye.",
            ],
        },
        "goodbye": {
            "openers": ["Apna khayal rakhiye.", "Bye for now.", "Shubh raatri.", "Phir milte hain.", "Theek hai, take care."],
            "repeat_openers": ["Phir se apna khayal rakhiye.", "Bye for now.", "Aapka din shaant rahe.", "Phir milte hain.", "Goodnight."],
            "templates": [
                "Jab chahein wapas aa sakte hain.",
                "Umeed hai aage ka din thoda halka lage.",
                "Aaj khud ke saath thoda gentle rahiye.",
                "Agar baad mein baat karni ho to main yahin hoon.",
                "Aapke liye ek shaant din ki wish karta hoon.",
                "Is baat ko hum baad mein phir se continue kar sakte hain.",
            ],
            "closers": [
                "Phir baat hogi.",
                "Take care.",
                "Main yahin rahunga jab zaroorat ho.",
                "Bye.",
                "Milte hain.",
            ],
        },
        "casual_checkin": {
            "openers": ["Main theek hoon, shukriya.", "Yahan sab theek hai.", "Main ready hoon help ke liye.", "Main theek chal raha hoon.", "Sab theek hai idhar."],
            "repeat_openers": ["Main abhi bhi theek hoon.", "Main yahin hoon.", "Sab theek hai idhar.", "Still ready to help.", "Main sun raha hoon."],
            "templates": [
                "Aap bataiye, aapka din kaisa ja raha hai?",
                "Aap kaise feel kar rahe ho aaj?",
                "Aapke side par kya chal raha hai?",
                "Aaj ka din aapko kaisa lag raha hai?",
                "Kya haal hai aapka?",
                "Lately sab kaisa chal raha hai?",
            ],
            "closers": [
                "Casual baat bhi theek hai, serious baat bhi theek hai.",
                "Aap jo chahein share kar sakte hain.",
                "Main chat ke liye bhi hoon aur help ke liye bhi.",
                "Jitna mann ho utna batayein.",
                "Main yahin hoon.",
            ],
        },
        "solution_request": {
            "openers": ["Chaliye isko simple banate hain.", "Iska next step dekhte hain.", "Hum practical tareeke se chalte hain.", "Isme chhota sa clear step nikaalte hain.", "Aapko abhi ek manageable plan dete hain."],
            "repeat_openers": ["Kyuki ye baat phir aa rahi hai, ek naya angle try karte hain.", "Is baar thoda alag tareeke se dekhte hain.", "Agar ye repeat ho raha hai to step ko aur simple karte hain.", "Chaliye approach thodi change karte hain.", "Main is baar thoda fresh next step deta hoon."],
            "templates": [
                "{topic} ke liye pehle body ko thoda settle kijiye: paani piyen, baithiye, aur saans ko dheere kijiye.",
                "Sab kuch ek saath fix karne ki jagah ek chhota helpful step chuniye aur wahi kijiye.",
                "Pehla kaam pressure kam karna hai, phir sochna hai. Body ko thoda calm karke next step lijiye.",
                "Abhi ke liye ek tiny plan rakhiye: ek calming step, ek practical step, aur baaki baad mein.",
                "{topic} mein aksar chhote steps zyada help karte hain, bada solution nahi.",
                "Pehle intensity kam kijiye, phir decision lijiye. Jaldi mein sab solve karna zaroori nahi hai.",
                "Ek minute ke liye slow breath aur ek useful action, abhi ke liye itna kaafi hai.",
                "Body aur mind ko thoda stable karke hi next cheez decide kijiye.",
                "Ek hi kaam chuniye jo abhi thoda relief de, wahi se start kijiye.",
                "Jo sabse aasaan aur helpful next step ho, usse shuru karna best rahega.",
            ],
            "closers": ["Agar detail doge to main aur specific bataunga.", "Aap ek line mein situation batayein, main next step clear karunga.", "Jo sabse mushkil part hai woh bata dijiye.", "Aapne kya try kiya hai woh batayein to main adjust karunga.", "Main isko aur tailored bana sakta hoon agar aap thoda aur batao."],
        },
        "symptom_report": {
            "openers": ["Ye uncomfortable lag raha hai.", "Samajh aa raha hai ki ye dikkat de raha hai.", "Main isko seriously le raha hoon.", "Ye sach mein thakane wala ho sakta hai.", "Is par dhyan dena banta hai."],
            "repeat_openers": ["Agar symptom abhi bhi hai to phir se calmly dekhte hain.", "Kyuki ye continue ho raha hai, isko thoda dhyan se assess karte hain.", "Lag raha hai ye abhi tak theek nahi hua.", "Is baar symptoms ko thoda aur clearly pakadte hain.", "Chaliye dobara practical tareeke se check karte hain."],
            "templates": [
                "{topic} kab se hai, kitna strong hai, aur saath mein aur kya ho raha hai, ye notice kijiye.",
                "Symptom ke case mein timing, severity, aur saath wale signs sabse important hote hain.",
                "Andaza lagane se better hai clearly observe karna: kab start hua, kitna badh raha hai, aur kya cheez trigger kar rahi hai.",
                "Pehle ye samajhiye ki symptom mild hai aur settle ho raha hai, ya strong hai aur worsen kar raha hai.",
                "Is tarah ke symptom mein duration aur intensity kaafi matter karti hai.",
                "Aap body ke signals ko concrete tareeke se note kijiye: kahan, kitna, aur kitni der se.",
                "Na ignore kijiye na panic. Seedhe signs note kijiye.",
                "Rest, hydration, aur red-flag symptoms par dhyan dena helpful rahega.",
                "{topic} ke saath agar koi aur naya symptom hai to woh bhi important hai.",
                "Sabse useful cheez abhi observation hai: symptom ka pattern clear kijiye.",
            ],
            "closers": ["Main aur specific tab ho paunga jab aap main symptom bataoge.", "Duration aur severity likh do to response aur clear hoga.", "Top do symptoms bata do, main narrow karunga.", "Jo symptom sabse zyada strong hai woh likho.", "Aap symptom ek line mein describe karo, main next step bataunga."],
        },
        "emotional_support": {
            "openers": ["Mujhe afsos hai ki ye itna heavy lag raha hai.", "Ye kaafi mushkil lag raha hai.", "Main mehsoos kar sakta hoon ki ye weighty hai.", "Samajh aa raha hai ki aap par pressure hai.", "Achha ki aapne ye andar nahi rakha."],
            "repeat_openers": ["Lag raha hai ye feeling abhi bhi saath hai.", "Agar ye baar-baar aa rahi hai to ise patience chahiye.", "Main dekh raha hoon ki ye abhi tak halka nahi hua.", "Chaliye is feeling ko thoda aur care ke saath handle karte hain.", "Hum same feeling ko ek naye response ke saath dekhte hain."],
            "templates": [
                "Abhi poori feeling ko solve karna zaroori nahi hai, bas ek steadying step lijiye.",
                "{topic} loud lage to goal bas itna rakhiye ki body thodi safe feel kare aur mind thoda slow ho.",
                "Agale kuch minutes ke liye pressure kam kijiye: jaw relax, shoulders loose, aur saans dheere.",
                "Ek slow breath cycle, thoda paani, aur ek kind sentence khud ko kehna helpful ho sakta hai.",
                "Aapko turant theek feel karna zaroori nahi hai, pehle body ko thoda calm hone dijiye.",
                "Soch ke saath ladne ki jagah pehle body ko thoda ground kijiye.",
                "Ye emotionally draining lag raha hai, isliye productivity se pehle steadiness chuniye.",
                "Jab feeling heavy ho to chhote grounding steps zyada kaam karte hain.",
                "Abhi ke liye bas agla minute naram aur manageable banaiye.",
                "Khud se thoda soft rahna abhi bahut zaroori hai.",
            ],
            "closers": ["Aap batayein ye zyada anxiety, sadness, stress, ya loneliness jaisa lag raha hai?", "Trigger kya tha woh ek line mein bata sakte hain.", "Jo part sabse heavy hai woh batayein.", "Main feeling ko aur clearly sort karne mein help kar sakta hoon.", "Aap chahein to bas itna bata dein ki ye kab strong hua."],
        },
        "emergency": {
            "openers": ["Main khush hoon ki aapne ye bola.", "Shukriya ye seedha batane ke liye.", "Main isko bahut seriously le raha hoon.", "Achha ki aapne reach out kiya.", "Ye baat important hai."],
            "repeat_openers": ["Main abhi bhi aapki safety par focused hoon.", "Kyuki ye phir aa raha hai, next steps bilkul clear rakhte hain.", "Main isko abhi bhi seriously le raha hoon.", "Safety ko hi priority rakhte hain.", "Aapki suraksha sabse pehle hai."],
            "templates": [
                "Kripya turant kisi trusted insaan, emergency service, ya nearest hospital se contact kijiye agar aap khud ko hurt kar sakte hain.",
                "Akele mat rahiye agar mumkin ho. Kisi bharosemand insaan ko abhi call ya message kijiye.",
                "Jo cheezein nuksan pahucha sakti hain unse door ho jaiye aur urgent help lijiye.",
                "Agar risk active lag raha hai to emergency help abhi lijiye.",
                "Kisi ko seedha batayein ki aap abhi safe mehsoos nahi kar rahe.",
                "Agale kuch minutes ka sirf ek kaam rakhiye: kisi insaan ke paas pahunchna.",
                "Nearest emergency room ya local emergency support tak pahunchna abhi sabse zaroori hai.",
                "Safety ke liye abhi real-world support lijiye, ye akela handle mat kijiye.",
                "Turant kisi ko call, text, ya saamne jaakar batayein ki situation urgent hai.",
                "Agar urge strong hai to abhi emergency madad lijiye aur akele na rahiye.",
            ],
            "closers": ["Reply karke batayein 'main safe hoon' ya 'main safe nahi hoon'.", "Batayein kya koi aapke saath hai?", "Kya aap akele hain abhi?", "Kya aapne kisi se contact kiya?", "Ek line mein safety status bata dijiye."],
        },
    },
    "hinglish": {
        "topic_labels": {
            "anxiety": "ghabrahat",
            "stress": "stress",
            "fatigue": "thakan",
            "physical_discomfort": "symptoms",
            "general": "jo chal raha hai",
        },
        "general_query": {
            "openers": ["Main yahin hoon.", "I am listening.", "Aap aaraam se bol sakte ho.", "Hum isse saath dekh lenge.", "Bolo, main dhyan se sun raha hoon."],
            "repeat_openers": ["Main abhi bhi yahin hoon.", "Hum isko thoda aur clear kar sakte hain.", "Lag raha hai ye baat abhi bhi heavy hai.", "Chalo isko phir se softly dekhte hain.", "Hum isse saath mein unpack karte hain."],
            "templates": [
                "Jo sabse important lag raha hai woh ek line mein bolo, main wahan se help karunga.",
                "Tum kya feel kar rahe ho, kya symptom hai, ya kis type ki help chahiye, usme se kahin se bhi start kar sakte ho.",
                "Perfect words ki zaroorat nahi hai, simple tareeke se bolo.",
                "Jo baat mind mein sabse loud chal rahi hai usse start karo.",
                "Mind ya body mein se abhi kya zyada bother kar raha hai, woh bata do.",
                "Ek short sentence bhi enough hai, main usse aage help kar dunga.",
                "Bas seedha bolo abhi sabse zyada kya disturb kar raha hai.",
                "Jo cheez sabse heavy lag rahi hai, uska naam le do.",
                "Jo aasaan lage uss point se start karo, main pick up kar lunga.",
                "Tum bas bolo, main isse practical aur supportive rakhunga.",
            ],
            "closers": ["Hum one message at a time chalenge.", "Tumhe sab kuch akela handle nahi karna.", "Main yahin hoon for the next step too.", "Hum isko manageable banayenge.", "Saath mein dekhte hain."],
        },
        "greeting": {
            "openers": ["Hey.", "Hello.", "Hi.", "Good to hear from you.", "Hey there."],
            "repeat_openers": ["Hey again.", "Hi again.", "Main yahin hoon.", "Hello dobara.", "Good to hear from you again."],
            "templates": [
                "Aaj kaisa chal raha hai?",
                "Bolo, aaj kis baat par chat karni hai?",
                "What is up on your side?",
                "Tum kahin se bhi start kar sakte ho.",
                "Jo mann mein ho woh bolo.",
                "How can I help today?",
            ],
            "closers": [
                "Hum isse simple rakh sakte hain.",
                "I am ready.",
                "Aaraam se bolo.",
                "Main sun raha hoon.",
                "Happy to chat.",
            ],
        },
        "gratitude": {
            "openers": ["You are welcome.", "Anytime.", "Khushi hui help karke.", "Of course.", "Glad to help."],
            "repeat_openers": ["Always welcome.", "Kabhi bhi.", "Glad I could help again.", "Bilkul.", "Happy to help."],
            "templates": [
                "Achha laga ki ye helpful raha.",
                "Mujhe khushi hai ki thoda kaam aaya.",
                "Glad it made things a bit easier.",
                "Thanks, ye sun kar achha laga.",
                "Jab chaho phir message kar sakte ho.",
                "Agar aur baat karni ho to main yahin hoon.",
            ],
            "closers": [
                "Hum aage bhi baat kar sakte hain.",
                "Feel free to message again.",
                "I am here if you need more help.",
                "Kabhi bhi wapas aa jao.",
                "Just send the next thing when you want.",
            ],
        },
        "goodbye": {
            "openers": ["Take care.", "Bye for now.", "Goodnight.", "See you soon.", "Theek hai, take care."],
            "repeat_openers": ["Take care again.", "Bye for now.", "Hope the rest of your day is calmer.", "Phir milte hain.", "Goodnight."],
            "templates": [
                "Jab chaaho wapas aa sakte ho.",
                "Hope aage ka din thoda lighter lage.",
                "Khud ke saath thoda gentle rehna.",
                "Come back anytime you want to talk.",
                "Wishing you a peaceful rest of the day.",
                "Hum baad mein phir se pick up kar sakte hain.",
            ],
            "closers": [
                "See you later.",
                "Talk soon.",
                "Main yahin hoon jab zaroorat ho.",
                "Bye.",
                "Take it easy.",
            ],
        },
        "casual_checkin": {
            "openers": ["Main theek hoon, thanks.", "Doing okay here.", "Main ready hoon chat ke liye.", "All good here.", "Pretty okay on my side."],
            "repeat_openers": ["Still okay here.", "Main yahin hoon.", "All good on my side.", "Still ready to help.", "Theek chal raha hai."],
            "templates": [
                "Tum batao, tumhara din kaisa ja raha hai?",
                "How are you feeling today?",
                "Tumhare side par kya chal raha hai?",
                "Aaj ka din kaisa lag raha hai?",
                "What is up with you today?",
                "Lately sab kaisa chal raha hai?",
            ],
            "closers": [
                "Casual baat bhi okay hai, real baat bhi okay hai.",
                "Jo mann ho woh share karo.",
                "I am here to chat or help, dono ke liye.",
                "Jitna chaaho utna bolo.",
                "Main yahin hoon.",
            ],
        },
        "solution_request": {
            "openers": ["Chalo isko simple banate hain.", "Let us keep this practical.", "Iska next step dekhte hain.", "Hum ek small plan nikaalte hain.", "Aao isse manageable karein."],
            "repeat_openers": ["Kyuki ye phir aa raha hai, ek fresh angle try karte hain.", "Is baar thoda different approach lete hain.", "Agar repeat ho raha hai to step aur simple karte hain.", "Chalo method thoda adjust karte hain.", "Main is baar thoda naya next step deta hoon."],
            "templates": [
                "{topic} ke liye pehle body ko thoda calm karo: paani, baithna, aur slow breathing.",
                "Sab kuch ek saath solve karne ki jagah ek useful step choose karo aur wahi karo.",
                "Pehle intensity down karo, phir decision lo.",
                "Ek tiny plan rakho: one calming step, one practical step, baaki baad mein.",
                "{topic} mein small actions usually zyada help karte hain.",
                "Body aur mind ko settle karke next cheez decide karna better rahega.",
                "Ek minute ke liye slow breath aur ek simple action, abhi ke liye kaafi hai.",
                "Jo sabse aasaan helpful step ho, usse start karo.",
                "Pressure thoda kam karo aur phir next move lo.",
                "Abhi bas one manageable next step choose karo.",
            ],
            "closers": ["Thoda aur detail doge to main aur specific ho jaunga.", "Situation ek line mein bata do, main narrow kar dunga.", "Hardest part batao, main us par focus karunga.", "Kya try kiya hai woh batao.", "Main isko aur tailored bana sakta hoon."],
        },
        "symptom_report": {
            "openers": ["Ye uncomfortable lag raha hai.", "I can see why this is bothering you.", "Main isko seriously le raha hoon.", "Ye body ke liye tiring ho sakta hai.", "Is par dhyan dena banta hai."],
            "repeat_openers": ["Agar symptom abhi bhi hai to dobara calmly check karte hain.", "Since ye continue ho raha hai, thoda detail mein dekhte hain.", "Lag raha hai ye abhi tak settle nahi hua.", "Chalo symptoms ko phir se clearly pakadte hain.", "Is baar thoda aur practical tareeke se assess karte hain."],
            "templates": [
                "{topic} kab start hua, kitna strong hai, aur saath mein aur kya ho raha hai, ye note karo.",
                "Timing, severity, aur extra symptoms yahan important hain.",
                "Guess karne ki jagah pattern observe karo: kab, kitna, aur kis cheez se badh raha hai.",
                "Pehle dekho mild hai aur settle ho raha hai ya strong hai aur worsen kar raha hai.",
                "Is type ke symptom mein duration aur intensity kaafi matter karti hai.",
                "Concrete tareeke se note karo: kahan, kitna, aur kitni der se.",
                "Na ignore karo, na panic. Signs clearly dekho.",
                "Rest aur hydration helpful hote hain, saath hi warning signs bhi dekho.",
                "{topic} ke saath aur koi naya symptom ho to woh bhi important hai.",
                "Abhi ka best step clear observation hai.",
            ],
            "closers": ["Main symptom bataoge to main aur specific guide karunga.", "Duration aur severity bhejo.", "Top 2 symptoms likh do.", "Jo symptom sabse strong hai woh bolo.", "Ek line mein describe karo, main next step bataunga."],
        },
        "emotional_support": {
            "openers": ["Mujhe afsos hai ki ye itna heavy lag raha hai.", "That sounds like a lot.", "Main sun sakta hoon ki ye weighty hai.", "Samajh aa raha hai ki pressure zyada hai.", "Achha ki tumne ye andar nahi rakha."],
            "repeat_openers": ["Lag raha hai ye feeling abhi bhi saath hai.", "Agar ye baar-baar aa rahi hai to isko patience chahiye.", "I can see ye abhi tak halka nahi hua.", "Chalo isko thoda aur care ke saath handle karte hain.", "Same feeling ko ek naye response ke saath dekhte hain."],
            "templates": [
                "Abhi poori feeling solve karna zaroori nahi hai, bas ek steadying step lo.",
                "{topic} loud lage to goal bas itna rakho ki body thodi safe feel kare.",
                "Agale kuch minutes ke liye pressure kam karo: jaw relax, shoulders loose, slow breath.",
                "Ek slow breath cycle, thoda paani, aur ek kind line khud ko kehna help kar sakta hai.",
                "Tumhe turant okay feel karna zaroori nahi hai, pehle body ko calm hone do.",
                "Thoughts se ladne se pehle body ko ground karo.",
                "Ye emotionally draining lag raha hai, isliye productivity se pehle steadiness choose karo.",
                "Heavy feeling mein small grounding steps usually better kaam karte hain.",
                "Abhi ka target bas next minute ko softer banana hai.",
                "Khud ke saath thoda gentle rehna abhi important hai.",
            ],
            "closers": ["Ye zyada anxiety, sadness, stress, ya loneliness jaisa lag raha hai?", "Trigger kya tha woh bata sakte ho.", "Sabse heavy part kaunsa hai?", "Main feeling ko aur sort karne mein help kar sakta hoon.", "Bas itna bata do ye kab strong hua."],
        },
        "emergency": {
            "openers": ["Main really glad hoon ki tumne ye bola.", "Thanks ye directly bolne ke liye.", "Main isko seriously le raha hoon.", "Achha ki tumne reach out kiya.", "Ye bahut important hai."],
            "repeat_openers": ["Main abhi bhi safety par focused hoon.", "Kyuki ye phir aa raha hai, next steps bilkul clear rakhte hain.", "Main isko abhi bhi seriously le raha hoon.", "Safety ko hi priority rakhte hain.", "Tumhari safety sabse pehle hai."],
            "templates": [
                "Please abhi kisi trusted person, emergency service, ya nearest hospital tak pahucho agar tum khud ko hurt kar sakte ho.",
                "Akele mat raho agar possible ho. Kisi trusted insaan ko abhi call ya text karo.",
                "Jo cheezein harm kar sakti hain unse door ho jao aur urgent help lo.",
                "Agar risk active lag raha hai to emergency help abhi lo.",
                "Kisi ko clearly batao ki tum abhi safe feel nahi kar rahe.",
                "Agale kuch minutes ka sirf ek kaam rakho: kisi insaan ke paas pahuchna.",
                "Nearest emergency room ya local emergency support tak jaana abhi sabse zaroori hai.",
                "Ye akela handle mat karo, real-world support lo.",
                "Abhi kisi ko call, text, ya saamne jaakar bolo ki situation urgent hai.",
                "Agar urge strong hai to please immediate help lo aur alone mat raho.",
            ],
            "closers": ["Reply karo: 'main safe hoon' ya 'main safe nahi hoon'.", "Kya koi tumhare saath hai?", "Kya tum akele ho abhi?", "Kya tumne kisi se contact kiya?", "Safety status ek line mein bata do."],
        },
    },
}
