# Keyword maps - Hindi (Devanagari + Roman transliteration)

SENTIMENT_MAP_HI = {
    "very_negative": [
        "मरना चाहता", "मरना चाहती", "जीना नहीं", "खुद को नुकसान",
        "जिंदगी खत्म", "बेकार हूँ", "mar jana chahta", "mar jana chahti",
        "jeena nahi", "zindagi khatam", "khud ko nuksan", "bekar hoon",
        "koi fayda nahi", "sab khatam", "jeene ka mann nahi",
        "khud ko hurt karna", "zinda nahi rehna", "marna hai",
        "mar jaau", "mar jau", "jeena nhi", "jina nahi", "jina nhi",
        "life khatam", "sab bekar", "khud ko harm", "apne aap ko nuksan",
    ],
    "negative": [
        "उदास", "दुखी", "परेशान", "थका", "थकी", "डरा", "डरी", "चिंता",
        "तनाव", "अकेला", "अकेली", "दर्द", "रोना", "बुरा", "बुरी",
        "udas", "dukhi", "pareshan", "thaka", "thaki", "dara", "dari",
        "chinta", "tanav", "akela", "akeli", "dard", "rona", "bura", "buri",
        "ghabrahat", "dar", "takleef", "mushkil", "bukhar", "sardi",
        "khansi", "kamzori", "ulti", "chakkar", "gala dard",
        "tension", "dukhi hu", "dukhi hun", "udas hu", "udas hun",
        "pareshan hu", "pareshan hun", "thak gya", "thak gaya",
        "thak gayi", "thk gya", "bura lg raha", "bura lag raha",
        "mann kharab", "man kharab", "dimag kharab", "dimaag kharab",
        "nind nahi", "neend nhi", "darr", "dar lag rha", "dar lag raha",
        "akele", "akela hu", "akeli hu", "low feel", "rona aa raha",
    ],
    "positive": [
        "खुश", "अच्छा", "ठीक", "बेहतर", "शांत", "आभारी",
        "khush", "accha", "theek", "behtar", "shant", "aabhari",
        "sukoon", "relief", "achha lag raha", "recovery", "theek ho raha",
        "acha", "achha", "thik", "thik hu", "theek hu", "better hu",
        "sahi hu", "mast", "relaxed", "calm hu", "ab theek",
    ],
}

INTENT_MAP_HI = {
    "emergency": [
        "मरना चाहता", "मरना चाहती", "जिंदगी खत्म करना", "खुद को नुकसान",
        "mar jana chahta", "mar jana chahti", "zindagi khatam karna",
        "khud ko nuksan", "jeena nahi chahta", "jeena nahi chahti",
    ],
    "solution_request": [
        "मदद करो", "क्या करूँ", "कैसे करूँ", "सुझाव", "उपाय",
        "madad karo", "kya karun", "kaise karun", "sujhav", "upay",
        "batao", "help karo", "kya karna chahiye", "tarika batao",
        "kaise theek", "solution batao", "ghar par kya karun",
        "kaise calm hoon", "kaise control karun", "kya karu", "kese karu",
        "kaise karu", "kya kru", "kese kru", "kya kru mai", "kya karu mai",
        "bta", "btao", "bta do", "bata do", "btana", "btaana",
        "help kro", "madad kro", "kya kru ab", "ab kya karu",
        "kaise hoga", "kese hoga", "kya solution hai", "upay btao",
        "kya khana chahiye", "kya lena chahiye", "kaise thik hoga",
        "samjhao", "smjhao", "guide kro", "guide karo", "detail me btao",
        "araam kaise milega", "relief kaise milega", "kya kru samajh nahi aa raha",
        "ab kya kru", "please bta", "pls bta", "jaldi btao", "kese theek hoga",
    ],
    "symptom_report": [
        "महसूस हो रहा", "सिरदर्द", "चक्कर", "घबराहट", "सांस",
        "mahsoos ho raha", "sar dard", "chakkar", "ghabrahat", "sans",
        "dil tez dhadak", "pet mein dard", "bukhar", "kamzori",
        "neend nahi", "sar ghoom", "sardi", "khansi", "gala kharab",
        "ulti", "dast", "jism dard", "seene mein jalan", "fever hai",
        "bukhar hai", "sardi hai", "jukam hai", "khasi hai", "khansi hai",
        "sar dard hai", "sir dard", "headache hai", "pet dard hai",
        "gala dukh raha", "gala kharab hai", "saans nahi aa rahi",
        "sans phool rahi", "dil tez dhadak raha", "chakkar aa raha",
        "kamjori hai", "weak feel", "body pain", "body dard",
        "neend nhi aa rahi", "nind nahi aa rahi", "mujhe dard hai",
    ],
    "emotional_support": [
        "उदास हूँ", "रो रहा", "रो रही", "अकेला", "अकेली",
        "udas hoon", "ro raha", "ro rahi", "akela", "akeli",
        "koi nahi samajhta", "dara hua", "dari hui", "pareshan hoon",
        "mann nahi lagta", "bahut bura lag raha", "thak gaya", "thak gayi",
        "support chahiye", "bahut low feel kar raha", "emotionally toot gaya",
        "udas hu", "udas hun", "akela hu", "akeli hu", "koi nhi samajhta",
        "koi nahi h", "mann nhi lagta", "man nahi lagta", "low hu",
        "low feel kar raha", "low feel kar rahi", "bahut tension hai",
        "mujhe support chahiye", "baat karni hai", "dil bhaari hai",
        "mera mood off hai", "mood off hai", "bahut ajeeb lag raha",
        "andar se toot raha hu", "andar se toot rahi hu", "dil nahi lag raha",
        "kisi se baat karni hai", "thoda support chahiye", "akela feel ho raha",
        "akeli feel ho rahi", "bahut stress me hu", "bahut stress me hun",
        "udas", "dukhi", "depressed", "hopeless", "empty", "numb",
        "anxious", "panic", "overthinking", "stressed", "isolated", "alone",
    ],
    "greeting": [
        "hello", "hi", "hey", "namaste", "namaskar", "good morning",
        "good evening", "good afternoon", "hii", "heyy",
    ],
    "gratitude": [
        "thanks", "thank you", "shukriya", "dhanyavaad", "thnx",
        "bahut shukriya", "appreciate it",
    ],
    "goodbye": [
        "bye", "goodnight", "good night", "see you", "milte hain",
        "phir milte hain", "take care", "bye bye",
    ],
    "casual_checkin": [
        "how are you", "kaise ho", "kaisi ho", "kaise hain", "kaisi hain",
        "kya haal hai", "kya haal", "what's up", "whats up", "sab kaisa chal raha hai",
    ],
}

INTENT_PATTERNS_HI = [
    {"intent": "emergency", "priority": 100, "keywords": INTENT_MAP_HI["emergency"]},
    {"intent": "solution_request", "priority": 80, "keywords": INTENT_MAP_HI["solution_request"]},
    {"intent": "symptom_report", "priority": 70, "keywords": INTENT_MAP_HI["symptom_report"]},
    {"intent": "emotional_support", "priority": 60, "keywords": INTENT_MAP_HI["emotional_support"]},
    {"intent": "casual_checkin", "priority": 35, "keywords": INTENT_MAP_HI["casual_checkin"]},
    {"intent": "gratitude", "priority": 34, "keywords": INTENT_MAP_HI["gratitude"]},
    {"intent": "goodbye", "priority": 33, "keywords": INTENT_MAP_HI["goodbye"]},
    {"intent": "greeting", "priority": 32, "keywords": INTENT_MAP_HI["greeting"]},
]

TOPIC_MAP_HI = {
    "anxiety": [
        "घबराहट", "चिंता", "बेचैनी", "दिल तेज",
        "ghabrahat", "chinta", "bechaini", "dil tez dhadak",
        "dar lag raha", "panic", "saans phool rahi", "kaanp raha",
        "dimag nahi ruk raha", "overthinking", "chest tight",
        "darr lag raha", "dar lag rha", "ghabra raha", "ghabra rahi",
        "bechain hu", "bechain hun", "dil ghabra raha", "panic ho raha",
        "saans tez", "sans tez", "dimag chal raha", "soch ruk nahi rahi",
        "dimag ghoom raha", "control nahi ho raha", "bahut uneasy lag raha",
        "andar ghabrahat ho rahi", "panic jaisa ho raha", "soch bohot aa rahi hai",
    ],
    "fatigue": [
        "थका", "थकी", "नींद नहीं", "नींद आती", "कमज़ोर",
        "thaka", "thaki", "neend nahi", "neend aati", "kamzor",
        "energy nahi", "lethargy", "uthne ka mann nahi", "hamesha thaka",
        "bilkul thak gaya", "body weak lag rahi", "thak gya", "thk gya",
        "energy nhi", "kamzori hai", "weak lag raha", "weak lag rahi",
        "uthne ka man nahi", "nind nahi", "nind nhi", "sleep nahi aa rahi",
        "bilkul drained hu", "drained feel ho raha", "body me energy nahi",
        "bahut sust lag raha", "so ke utha fir bhi thaka hu",
    ],
    "stress": [
        "तनाव", "दबाव", "बोझ", "काम का",
        "tanav", "dabav", "bojh", "kaam ka",
        "bahut kaam", "deadline", "jimmedari", "overwhelmed",
        "bahut pressure", "rest nahi milta", "exam pressure", "family pressure",
        "tension", "pressure hai", "kaam ka pressure", "padhai pressure",
        "exam tension", "ghar ka pressure", "dimag heavy", "bohot kaam",
        "kaam bahut hai", "stress ho raha", "stressed hu", "stressed hun",
        "sab kuch ek sath aa gaya", "handle nahi ho raha", "manage nahi ho raha",
        "mind pe load hai", "dimaag pe pressure hai", "kaam ka load zyada hai",
    ],
    "physical_discomfort": [
        "सिरदर्द", "उल्टी", "चक्कर", "सीने में दर्द",
        "sar dard", "ulti", "chakkar", "seene mein dard",
        "pet dard", "bukhar", "dizziness", "chest tight", "body dard",
        "sardi", "khansi", "gala dard", "naak band", "jukam", "dast",
        "jodon mein dard", "kamzori", "sir dard", "headache", "fever",
        "cold", "cough", "khasi", "gala kharab", "gale me dard",
        "saans phoolna", "sans phoolna", "pet me dard", "stomach pain",
        "loose motion", "body pain", "body ache", "weakness", "chakkar aa raha",
        "tabiyat kharab lag rahi", "tabiyat kharab hai", "body toot rahi",
        "seene me jalan", "gala me jalan", "sir bhaari hai", "pet kharab hai",
        "malaria", "jaundice", "peeliya", "peelia", "dengue", "typhoid", "migraine", "flu",
    ],
}
